Repository cisco-ie/cisco-gnmi-python, pull requests merged in 2019-10, with the labels that each got.

#15 NX-OS Client Wrapper
  src/cisco_gnmi/__init__.py
  src/cisco_gnmi/builder.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/util.py
Labels: enhancement

#21 Fixed xpath duplicate origin in XR client
  src/cisco_gnmi/xr.py
Labels: bug, feature

#26 IOS XE Client
  README.md
  scripts/.gitignore
  scripts/gen_certs.sh
  src/cisco_gnmi/__init__.py
  src/cisco_gnmi/builder.py
  src/cisco_gnmi/xe.py
Labels: enhancement, feature

#20 Adding Makefile, docs and Tests for util.py & auth.py
  Makefile
  Pipfile
  README.md
  hygiene.sh
  requirements.txt
  setup.py
  tests/README.md
  tests/__init__.py
  tests/test_auth.py
  tests/test_util.py
Labels: enhancement, test

#29 Remove direct reference to proto enums for protobuf < 3.8.0
  src/cisco_gnmi/client.py
Labels: bug, refactor

#30 Replace proto append with extend for protobuf < 3.8.0
  src/cisco_gnmi/client.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/xe.py
  src/cisco_gnmi/xr.py
Labels: bug, refactor

#31 Move SSL target override into builder construct
  src/cisco_gnmi/builder.py
Labels: bug, refactor

#32 Add PyPi packaging to Makefile
  Makefile
Labels: enhancement, ergonomics
