Repository cisco-ie/cisco-gnmi-python, pull requests merged in 2020-07, with the labels that each got.

#67 Added missing functions for nx.py class
  src/cisco_gnmi/__init__.py
  src/cisco_gnmi/client.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/xe.py
Labels: enhancement, feature, os/nx, os/xe

#73 Create NOTICE
  NOTICE
Labels: documentation, enhancement

#63 parse_xpath_to_gnmi_path as classmethod
  src/cisco_gnmi/client.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/xe.py
  src/cisco_gnmi/xr.py
Labels: enhancement, ergonomics

#75 Release v1.0.12
  src/cisco_gnmi/__init__.py
  src/cisco_gnmi/cli.py
  src/cisco_gnmi/client.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/xe.py
  src/cisco_gnmi/xr.py
Labels: enhancement, feature

#76 Revert "Release v1.0.12"
  src/cisco_gnmi/__init__.py
  src/cisco_gnmi/cli.py
  src/cisco_gnmi/client.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/xe.py
  src/cisco_gnmi/xr.py
Labels: bug

#77 Release v1.0.13 (Fixed v1.0.12)
  src/cisco_gnmi/__init__.py
  src/cisco_gnmi/cli.py
  src/cisco_gnmi/client.py
  src/cisco_gnmi/nx.py
  src/cisco_gnmi/xe.py
  src/cisco_gnmi/xr.py
Labels: enhancement, ergonomics
